### ISSUE TITLE
OpenSource dev ecosystem call

### ISSUE THREAD

**Issue by shivgupt** [daostack/Ecosystem#9]
What time suites you the most for the DAOstack dev Ecosystem call?
If non of the time options work for you please leave a preferred time in comments

[![](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/1500%20GMT+1)](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/1500%20GMT+1/vote)
[![](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/1800%20GMT+1)](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/1800%20GMT+1/vote)
[![](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/2300%20GMT+1)](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/2300%20GMT+1/vote)
[![](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/none%20of%20these)](https://api.gh-polls.com/poll/01DRBKA2WJK4D2209G7T4CK3AZ/none%20of%20these/vote)

**Comment by wkarshat** [comment]
Starting at 20:00 GMT+1

**Comment by shivgupt** [comment]
Tracking the time via the [signup form ](https://airtable.com/shrdI76SOnGYkYeci)
